name: crave
favicon: null
layout_spectrum: 0.683529521105811
typography_spectrum: 0.17024724348448217
title: What Makes Your World Go Round
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#95d600'
    - '#ffffff'
    - '#9a9a9a'
    - '#4a6a00'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.44646478234790266
  rhythmicContrast: 0.75
purpose: []
